### ISSUE TITLE
Does not work with Virginia Tech URLs

### ISSUE THREAD

**Issue by sakgoyal** [oliver-ni/web-cat-vscode#14]
Is there a way to add support for the way that Virginia Tech handles their submission URLs?

[https://web-cat.cs.vt.edu/Web-CAT/WebObjects/Web-CAT.woa/wa/assignments/eclipse?institution=VT](https://web-cat.cs.vt.edu/Web-CAT/WebObjects/Web-CAT.woa/wa/assignments/eclipse?institution=VT)
This link has all of the information to submit in the same place instead of having them in 2 different URLs

**Comment by oliver-ni** [comment]
Hiya, if I understand this correctly you should just be able to add this to submitUrls. You can ignore Snarfer Browser since as I understand that is something unrelated to web-cat that my high school used for assignment download.
